"""Node 6: Generates a human-readable investigation narrative. Uses LLM with template fallback."""
import os
import json

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

from src.agents.state import AgentState
from src.agents.observability import traced

load_dotenv()

GEMINI_MODEL = "gemini-2.5-flash-lite"


def _template_narrative(state: AgentState) -> str:
    merchant = state.get("merchant_info", {})
    txn = state.get("transactions_summary", {})
    kyb = state.get("kyb_status", {})
    context = state.get("context_findings", [])
    decision = state.get("decision", "REVIEW")
    explanation = state.get("explanation", "")
    counterfactual = state.get("counterfactual", "")
    codes = state.get("reason_codes", [])

    context_text = "\n".join(
        f"  - [{f.get('classification', 'N/A')}] {f.get('finding', 'N/A')}"
        for f in context
    ) or "  No external context findings."

    feature_text = "\n".join(
        f"  - {f['feature']}: {f['importance']:.4f}"
        for f in state.get("feature_importances", [])[:5]
    )

    return f"""# Investigation Report — {merchant.get('name', 'Unknown Merchant')}

## Summary
Merchant **{merchant.get('name')}** (MCC {merchant.get('mcc_code')} — {merchant.get('mcc_description')}) in {merchant.get('city')}, {merchant.get('state')} was flagged for anomalous transaction activity.

**Decision: {decision}** (Confidence: {state.get('confidence', 0):.0%})
**Reason Codes**: {', '.join(codes)}

## Transaction Analysis
- Transactions (24h): {txn.get('txn_count_24h', 0)}
- Average ticket: ${txn.get('avg_amount_24h', 0):.2f}
- Total volume (24h): ${txn.get('total_amount_24h', 0):.2f}
- Unique customers: {txn.get('unique_customers_24h', 0)}
- Card present: {txn.get('pct_card_present', 0):.0%}
- International: {txn.get('pct_international', 0):.0%}

## ML Risk Assessment
- Risk probability: {state.get('risk_score', 0):.3f}
- Anomaly score: {state.get('anomaly_score', 0):.3f}
- Peer volume z-score: {state.get('peer_zscore', 0):.1f}σ
- Top risk factors:
{feature_text}

## Contextual Investigation
{context_text}

## KYB Verification
- Business age: {kyb.get('business_age_days', 'N/A')} days
- Sanctions screening: {'CLEAR' if kyb.get('sanctions_clear') else 'FLAG'}
- PEP screening: {'CLEAR' if kyb.get('pep_clear') else 'FLAG'}
- Overall: {kyb.get('overall', 'N/A')}

## Decision Rationale
{explanation}

## Counterfactual
{counterfactual}

## Model Versions
{json.dumps(state.get('model_versions', {}), indent=2)}

---
*Report generated by Risk Copilot — Agentic Decision Engine*
"""


@traced(name="narrative_generator")
def narrative_generator(state: AgentState) -> dict:
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        report = _template_narrative(state)
        return {
            "narrative_report": report,
            "reasoning_trace": [f"[NarrativeGenerator] Template report generated ({len(report)} chars). No API key."],
        }

    try:
        llm = ChatGoogleGenerativeAI(model=GEMINI_MODEL, google_api_key=api_key, temperature=0.2)

        evidence_summary = json.dumps({
            "merchant": state.get("merchant_info", {}),
            "transactions": state.get("transactions_summary", {}),
            "risk_score": state.get("risk_score"),
            "anomaly_score": state.get("anomaly_score"),
            "peer_zscore": state.get("peer_zscore"),
            "feature_importances": state.get("feature_importances", [])[:5],
            "context_findings": state.get("context_findings", []),
            "kyb_status": state.get("kyb_status", {}),
            "decision": state.get("decision"),
            "confidence": state.get("confidence"),
            "reason_codes": state.get("reason_codes", []),
            "explanation": state.get("explanation"),
            "counterfactual": state.get("counterfactual"),
            "model_versions": state.get("model_versions", {}),
        }, indent=2, default=str)

        prompt = f"""You are a compliance report writer at a payment processor. Generate a professional investigation narrative.

EVIDENCE:
{evidence_summary}

Write a structured report with these sections:
1. **Summary** — One paragraph: who, what, when, decision
2. **Transaction Analysis** — Key metrics that triggered the alert
3. **Risk Assessment** — ML model findings and peer comparison
4. **Contextual Investigation** — External factors found (or not found)
5. **KYB Verification** — Business verification status
6. **Decision Rationale** — Why this decision was made, connecting evidence to policy
7. **Counterfactual** — What would change the decision (important for audit)
8. **Model Versions** — Which models were used (for regulatory replay)

REQUIREMENTS:
- Professional tone suitable for regulatory review
- Do NOT expose raw LLM reasoning chains
- Use precise language, avoid hedging
- Include all model versions for audit trail
- End with "Report generated by Risk Copilot — Agentic Decision Engine"

Write in markdown format."""

        response = llm.invoke(prompt)
        report = response.content

        return {
            "narrative_report": report,
            "reasoning_trace": [f"[NarrativeGenerator] LLM report generated ({len(report)} chars)."],
        }

    except Exception as e:
        report = _template_narrative(state)
        return {
            "narrative_report": report,
            "reasoning_trace": [f"[NarrativeGenerator] LLM failed ({type(e).__name__}), used template ({len(report)} chars)."],
        }
